### ISSUE TITLE
Zaribo 220 

### ISSUE THREAD

**Issue by merlin2k** [bgiot/Prusa-Firmware-BMG#2]
Can you give us a Zaribo Version of the Mk3 / Mk3s Firmware? Just the z heigh change to 220..
that would be nice

**Comment by bgiot** [comment]
Sorry, but then I open to support more and more printers. As I only have a MK3, it will become difficult.
You can fork my fork (bgiot/Prusa-Firmware  branch BMGCustom)

**Comment by merlin2k** [comment]
I only need the modified source files.. i can change the z heigh and compile by myself.
would that be okay?

**Comment by bgiot** [comment]
The modified source code is here:
https://github.com/bgiot/Prusa-Firmware/tree/BMGCustom
I used Microsoft VS Code + platform.io addin for compiling.
