### ISSUE TITLE
MK25s with inverted extruder direction?

### ISSUE THREAD

**Issue by zawadzkip** [bgiot/Prusa-Firmware-BMG#4]
Any chance you can make a variant of the MK2.5S build with
```c
#define INVERT_E0_DIR 0    // for direct drive extruder v9 set to 1, for geared extruder set to 0
#define INVERT_E1_DIR 0    // for direct drive extruder v9 set to 1, for geared extruder set to 0
#define INVERT_E2_DIR 0    // for direct drive extruder v9 set to 1, for geared extruder set to 0
```

having some issues compiling :/

**Comment by zawadzkip** [comment]
Did manage to get it to compile, if you'd like I can submit a PR, but it's minor changes.

**Comment by bgiot** [comment]
Did you create a variant? For which printer is it?
From original configs, MK2/2.5 use a direct drive and MK3/3S use geared extruder. right?
BMG for MK2.5 becomes a geared extruder? So I need to change. So the MK2.5/MK2.5S version I have release are buggy because filament in going in the wrong direction? or we need to have the two options depending of (I don't know what….)?

**Comment by bgiot** [comment]
If you use the cable provided by Bondtech, you don't need to change the E motor direction…

**Comment by zawadzkip** [comment]
@bgiot I will double check on the cable. I may have missed that part during assembly but I believe I am using that cable.... But yes I believe the BMG + MK2.5S needs the inversion.

https://www.bondtech.se/en/customer-service/faq/ Note the "extruder turning in the wrong direction" 

Edit: https://www.bondtech.se/en/product/prusa-i3-mk2-mk2s-extruder-upgrade/ This upgrade is what I used to upgrade, and it uses the pancake stepper motor, which seems to require the firmware change.

**Comment by bgiot** [comment]
@zawadzkip You maybe need to swap some cables.  Many people confirmed that you just have to put cables in the right order to fix your issue.  This will avoid to have another firmware build to maintain.
Regards.
