### ISSUE TITLE
Support menu shows wrong version on latest build

### ISSUE THREAD

**Issue by WarrenSchultz** [bgiot/Prusa-Firmware-BMG#5]
Minor issue, but it shows as 3.7.0 instead of 3.7.1 on the latest build.

**Comment by bgiot** [comment]
I noticed it. The dev team of Prusa forgot to update the version information.  I already communicate it on the facebook community group.
![image](https://user-images.githubusercontent.com/379959/57433975-19ead200-723a-11e9-9ada-53b5cadcdf38.png)
