### ISSUE TITLE
Extruder Clicking/Rattling on Retractions

### ISSUE THREAD

**Issue by bobbyromeo** [bgiot/Prusa-Firmware-BMG#9]
I'm noticing an odd clicking / rattling sound coming from the extruder. It appears to happen on
retractions mostly. Is this sound normal? Is it due to the PLA rubbing on a
part of the extruder? Or perhaps the gears meshing together?

I've uploaded a short video demonstrated this sound: https://streamable.com/30de7

According to Bondtech support, "The linear advance used with original Prusa firmware will create this sound due to the gearing ratio, try by disabling the Linear Advance and the sound should go away. There is a new version that implements the latest version of the Linear advance that will work much better."

**Comment by bgiot** [comment]
This sound is normal. Indeed linked to retraction. You can eventually reduce the retraction distance... LA 1.5 should solve this indeed...

**Comment by bobbyromeo** [comment]
Thanks again.
Where is this changed?
The line in PrusaSlicer?

`M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}15{else}30{endif} ; Filament gcode`

If this is the place to change it, wouldn't 1.5 be too low? Or you mean 15?
Also, I'm assuming it will also affect print quality?

**Comment by bgiot** [comment]
Indeed this setting must be change to cope with LA 1.5.  Which LA1.5 firmware did you take ?

**Comment by bobbyromeo** [comment]
I'm not sure what you mean. I compiled the firmware based on your https://github.com/bgiot/Prusa-Firmware/tree/BMGCustom branch.
How do you change LA to 1.5 in the code?

**Comment by bgiot** [comment]
It's not just config... search the facebook community group to find LA15 custom firmware. Mine doesn't have the custom part for LA15

**Comment by bobbyromeo** [comment]
I'm looking...having trouble finding it.
**Edit**: Ok think I found it. https://github.com/vertigo235/Build-Prusa-LA-15/releases/tag/3.7.2_MK3S_LA15_FINAL

I guess it's this file: FW372-Build1561750301-1_75mm_MK3S-BMG-16-EINSy10a-E3Dv6full.hex

**Comment by bgiot** [comment]
I think so, if you have an MK3**S**
